apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: templatedeploy
  name: templatedeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: templatedeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: templatedeploy
    spec:
      containers:
      - image: deploy/dockernode
        imagePullPolicy: Never  ##IMAGENS LOCAIS
        name: dockernode
        resources: {}
        ports:
          - containerPort: 3000
status: {}
